use_frameworks!

target 'Example iOS' do
  platform :ios, '9.0'

  pod 'L10n-swift', :path => './../'
end

target 'Example macOS' do
  platform :osx, '10.10'
  
  pod 'L10n-swift', :path => './../'
end

target 'Example tvOS' do
  platform :tvos, '9.0'
  
  pod 'L10n-swift', :path => './../'
end

target 'Example watchOS Extension' do
  platform :watchos, '9.0'
  
  pod 'L10n-swift', :path => './../'
end
